# Netlify Configuration for ParkStay Pass
# Production deployment with Solana Devnet connectivity

[build]
  command = "pnpm install && pnpm run build"
  publish = "dist"
  
[build.environment]
  NODE_VERSION = "20"
  
  # Solana Network Configuration - DEVNET for production
  VITE_SOLANA_NETWORK = "devnet"
  
  # Enable demo mode toggle (users can switch between demo and live wallet modes)
  VITE_ENABLE_DEMO_MODE = "true"
  
  # Solana RPC Endpoints
  VITE_SOLANA_RPC_DEVNET = "https://api.devnet.solana.com"
  VITE_SOLANA_RPC_TESTNET = "https://api.testnet.solana.com"
  VITE_SOLANA_RPC_MAINNET = "https://api.mainnet-beta.solana.com"

# Redirect all requests to index.html for client-side routing (SPA)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security and CORS headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    # CORS for Solana RPC calls
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type"

# Cache static assets for 1 year
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache images
[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache fonts
[[headers]]
  for = "*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Don't cache HTML files
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Dev server settings for Netlify Dev
[dev]
  command = "pnpm run dev"
  port = 5000
  targetPort = 5000
  autoLaunch = false
